using System;

namespace HyperStation.GameServer.Network.Packet.GameServer
{
    public enum GoodsType
    {
        GOODS_TYPE_HYPER = 1,
        GOODS_TYPE_EQUIP_ITEM,
        GOODS_TYPE_PACKAGE,
        GOODS_TYPE_EMBLEM,
        GOODS_TYPE_BOOSTER,
        GOODS_TYPE_SKIN,
        GOODS_TYPE_SLOT,
        GOODS_TYPE_NAME_CHANGE,
        GOODS_TYPE_EMBLEM_SLOT,
        GOODS_TYPE_HYPER_EMOTION,
        GOODS_TYPE_GAME_POINT,
        GOODS_TYPE_HYPER_SLOT,
        GOODS_TYPE_CUBE,
        GOODS_TYPE_CRAFT_MATERIAL,
        GOODS_TYPE_CRAFT_PIECE_HYPER,
        GOODS_TYPE_CRAFT_PIECE_SKIN,
        GOODS_TYPE_CRAFT_PIECE_EQUIP,
        GOODS_TYPE_CRAFT_PIECE_SLOT,
        GOODS_TYPE_CRAFT_PIECE_EMOTION,
        GOODS_TYPE_CRAFT_PIECE_EMBLEM,
        GOODS_TYPE_EXCHANGE_TICKET
    }
}
